*
      Real           tIsl, teIsl, TCellIsl1, TCellIsl2
      Common/zIsl06/ tIsl(                nI_Max),
     +               teIsl(               nI_Max),
     +               TCellIsl1(Nr_cIslMax,nI_Max),
     +               TCellIsl2(Nr_cIslMax,nI_Max)
*
      Integer   NrCells
      Real      TCell1( Nr_cIslMax), TCell2( Nr_cIslMax)
      Real      ECell(  Nr_cIslMax)
      Real      ImbCell(Nr_cIslMax)
      Real      Time, Timerr
