#___________________________________________________________________________
#
#		Pull in Machine-dependent local locations:
#
#___________________________________________________________________________
#
#  For running the Debugger, it's easier to use the default EXEDIR.
#  But, this can be used to create the executable on the scratch area:
#  ------------------------------------------------------------------
#EXEDIR=/tmp/jryan$(ZARCH_TYPER)
#___________________________________________________________________________
#
#    Definitions for FPP
#___________________________________________________________________________
#
CONDITIONAL_FLAGS =  #
#
CONDITIONAL_FLAGS_OFF =  #
#___________________________________________________________________________
#
#    Definitions for FPP
#___________________________________________________________________________
#
#  For running the Debugger, one must use the debug Linker flag:
DEBUG_LIBRARY=ON
#
# to get BPTRECON before 1997
ZEUSRELEASE = pro
#LD_OPTS += -g
#____________________________________________________________________
#
